using Microsoft.Agents.AI;
using Microsoft.Extensions.AI;
using SmartShoppingAssistant.BusinessLogic.Agents.Interfaces;
using SmartShoppingAssistant.BusinessLogic.Models;
using SmartShoppingAssistant.BusinessLogic.Services.Interfaces;
using SmartShoppingAssistant.BusinessLogic.Tools;
using System.ComponentModel;

namespace SmartShoppingAssistant.BusinessLogic.Agents
{
    public class SuggestionComposerAgent(IChatClient chatClient, IProductService productService) : ISuggestionComposerAgent
    {
        public ChatClientAgent Build(string cartJson, string availableCategoriesJson)
        {
            return new ChatClientAgent(
            chatClient,
            new ChatClientAgentOptions
            {
                Name = "SuggestionComposer",
                Description = "Generates targeted product suggestions to help users unlock near-miss promotions.",
                ChatOptions = new ChatOptions
                {
                    Instructions = $"""
                        You are a highly efficient e-commerce recommendation engine.

                        --- INPUT DATA ---
                        1. User Cart: {cartJson}
                        2. Available Categories: {availableCategoriesJson}
                        3. Promotion Analysis (Near Misses): YOU MUST READ THE PREVIOUS MESSAGE IN THIS CONVERSATION to find the Near-Miss deals generated by the Promotion Evaluator.

                        --- CORE OBJECTIVE ---
                        Suggest EXACTLY 5 products. Prioritize products that fulfill the 'action' required to activate the near-miss deals. 
                        If there are no near-misses, suggest relevant cross-sell items based on the user's cart.

                        --- SAVINGS CALCULATION (MANDATORY) ---
                        For EVERY suggested item tied to a promotion, you MUST explicitly calculate the savings the user will gain.
                        - Savings = (Original Price - Price after promotion).
                        - Product/Category Deals: Calculate savings based on the specific item/category threshold.
                        - Cart-wide Deals: Calculate savings based on the new total cart value.
                        *You must show your math in the explanation field before outputting the final number.*

                        --- STRICT CONSTRAINTS & TOOL USAGE ---
                        - DO NOT HALLUCINATE. You must ONLY suggest products returned by your Tools. Do not invent names, IDs, or prices.
                        - If a near-miss requires "8.00 RON", you may suggest a 10.00 RON item to ensure they clear the threshold safely.
                        - OPTIMIZE TOOL CALLS: Do not paginate sequentially. Make ONE call to 'SearchProducts' per required category using 'page: 1' and a high 'pageSize' (e.g., 20 or 30) to get all the options you need at once.

                        --- STEP-BY-STEP PROCESS ---
                        1. Analyze the previous message's Near Misses to determine target Category IDs and maximum prices.
                        2. Call 'SearchProducts' using page=1 and pageSize=20.
                        3. Select the best items from the results.
                        4. Calculate the exact math for the 'Savings' property for each item.
                        5. Output the final JSON containing the 5 items.
                        """,
                    ResponseFormat = ChatResponseFormat.ForJsonSchema<AnalysisResponse>(),
                    Tools =
                    [
                        AIFunctionFactory.Create(
                            ([Description("The exact ID of the category to search. Use null if searching the entire store.")] int? categoryId,
                             [Description("The maximum price the user should pay to complete a near-miss promotion.")] decimal? maxPrice,
                             [Description("Always set this to 1 to avoid pagination loops.")] int page,
                             [Description("Set this to a high number (e.g., 20) to get plenty of options in one request.")] int pageSize
                             ) =>
                                ShoppingTools.SearchProducts(categoryId, maxPrice, page, pageSize, productService),
                            "SearchProducts",
                            "Searches the store for products. Use this to find items that fulfill near-miss promotions."
                        ),

                        AIFunctionFactory.Create(
                            ([Description("The exact ID of the product.")] int productId) =>
                                ShoppingTools.GetProductById(productId, productService),
                            "GetProductById",
                            "Gets the exact details of a specific product by its ID."
                        )
                    ]
                }
            },
            null!,
            null!
        );
        }
    }
}