// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartShoppingAssistant.DataAccess;

#nullable disable

namespace SmartShoppingAssistant.DataAccess.Migrations
{
    [DbContext(typeof(SmartShoppingAssistantDbContext))]
    [Migration("20260511160444_InitialSeeding")]
    partial class InitialSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductCategories", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 1,
                            CategoryId = 7
                        },
                        new
                        {
                            ProductId = 1,
                            CategoryId = 9
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 7
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 10
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 7
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 8
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 9
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 7
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 8
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 10
                        });
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CartId = 1,
                            ProductId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            CartId = 1,
                            ProductId = 13,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 3,
                            CartId = 1,
                            ProductId = 11,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 4,
                            CartId = 2,
                            ProductId = 7,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 5,
                            CartId = 2,
                            ProductId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 6,
                            CartId = 3,
                            ProductId = 6,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 7,
                            CartId = 3,
                            ProductId = 10,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 8,
                            CartId = 4,
                            ProductId = 4,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 9,
                            CartId = 4,
                            ProductId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 10,
                            CartId = 5,
                            ProductId = 9,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 11,
                            CartId = 5,
                            ProductId = 18,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Gadgets, smartphones, audio, and home entertainment systems.",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Laptops, desktops, monitors, components, and networking gear.",
                            Name = "Computers & Accessories"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Furniture, decor, appliances, and kitchenware.",
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Apparel and accessories for men, women, and kids.",
                            Name = "Clothing, Shoes & Jewelry"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Skincare, makeup, haircare, and grooming products.",
                            Name = "Beauty & Personal Care"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Fiction, non-fiction, educational, and audiobooks.",
                            Name = "Books"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Fitness equipment, outdoor gear, and athletic clothing.",
                            Name = "Sports & Outdoors"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Board games, action figures, puzzles, and educational toys.",
                            Name = "Toys & Games"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Vitamins, supplements, cleaning supplies, and medical care.",
                            Name = "Health & Household"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Car parts, accessories, tools, and car care products.",
                            Name = "Automotive"
                        });
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DiscountTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("ExpectedArrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products", null, t =>
                        {
                            t.HasCheckConstraint("CK_Product_Stock_NonNegative", "[Stock] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Tracks heart rate, sleep, and workouts with GPS.",
                            ImageUrl = "https://via.placeholder.com/300?text=Smartwatch",
                            Name = "Smart Fitness Watch",
                            Price = 199.99m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 2,
                            Description = "15.6-inch display, 16GB RAM, 1TB SSD, RTX 4060.",
                            ImageUrl = "https://via.placeholder.com/300?text=Gaming+Laptop",
                            Name = "Pro Gaming Laptop",
                            Price = 1299.00m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 3,
                            Description = "12-cup drip coffee maker with programmable timer.",
                            ImageUrl = "https://via.placeholder.com/300?text=Coffee+Maker",
                            Name = "Programmable Coffee Maker",
                            Price = 59.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 4,
                            Description = "Breathable, 100% cotton everyday crewneck t-shirt.",
                            ImageUrl = "https://via.placeholder.com/300?text=T-Shirt",
                            Name = "Men's Classic Cotton T-Shirt",
                            Price = 15.00m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 5,
                            Description = "Lightweight athletic sneakers with shock absorption.",
                            ImageUrl = "https://via.placeholder.com/300?text=Running+Shoes",
                            Name = "Women's Running Shoes",
                            Price = 75.00m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 6,
                            Description = "Gentle daily cleanser with hyaluronic acid.",
                            ImageUrl = "https://via.placeholder.com/300?text=Cleanser",
                            Name = "Hydrating Facial Cleanser",
                            Price = 18.50m,
                            Stock = 90
                        },
                        new
                        {
                            Id = 7,
                            Description = "An epic space adventure across uncharted star systems.",
                            ImageUrl = "https://via.placeholder.com/300?text=Sci-Fi+Book",
                            Name = "The Great Galaxy - Sci-Fi Novel",
                            Price = 12.99m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 8,
                            Description = "Extra thick exercise mat with carrying strap.",
                            ImageUrl = "https://via.placeholder.com/300?text=Yoga+Mat",
                            Name = "Non-Slip Yoga Mat",
                            Price = 22.00m,
                            Stock = 110
                        },
                        new
                        {
                            Id = 9,
                            Description = "Cooperative family board game for 2-6 players.",
                            ImageUrl = "https://via.placeholder.com/300?text=Board+Game",
                            Name = "Mystery Detective Board Game",
                            Price = 29.50m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 10,
                            Description = "Daily vitamins with essential nutrients for adults.",
                            ImageUrl = "https://via.placeholder.com/300?text=Vitamins",
                            Name = "Multivitamin Gummies",
                            Price = 14.99m,
                            Stock = 130
                        },
                        new
                        {
                            Id = 11,
                            Description = "Front recording with night vision capabilities.",
                            ImageUrl = "https://via.placeholder.com/300?text=Dash+Cam",
                            Name = "1080p Dash Cam",
                            Price = 65.00m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 12,
                            Description = "Waterproof wireless speaker with 12-hour battery.",
                            ImageUrl = "https://via.placeholder.com/300?text=Speaker",
                            Name = "Portable Bluetooth Speaker",
                            Price = 45.99m,
                            Stock = 65
                        },
                        new
                        {
                            Id = 13,
                            Description = "Comfortable grip with adjustable DPI.",
                            ImageUrl = "https://via.placeholder.com/300?text=Mouse",
                            Name = "Ergonomic Wireless Mouse",
                            Price = 29.99m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 14,
                            Description = "1000W motor for smoothies, soups, and crushing ice.",
                            ImageUrl = "https://via.placeholder.com/300?text=Blender",
                            Name = "High-Speed Blender",
                            Price = 89.99m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 15,
                            Description = "Insulated, water-resistant jacket for cold weather.",
                            ImageUrl = "https://via.placeholder.com/300?text=Winter+Jacket",
                            Name = "Winter Puffer Jacket",
                            Price = 110.00m,
                            Stock = 55
                        },
                        new
                        {
                            Id = 16,
                            Description = "Brightening serum for uneven skin tones.",
                            ImageUrl = "https://via.placeholder.com/300?text=Face+Serum",
                            Name = "Vitamin C Face Serum",
                            Price = 24.00m,
                            Stock = 85
                        },
                        new
                        {
                            Id = 17,
                            Description = "100 quick recipes for the whole family.",
                            ImageUrl = "https://via.placeholder.com/300?text=Cookbook",
                            Name = "Healthy Weeknight Meals Cookbook",
                            Price = 24.99m,
                            Stock = 70
                        },
                        new
                        {
                            Id = 18,
                            Description = "Space-saving weights adjustable from 5 to 52 lbs.",
                            ImageUrl = "https://via.placeholder.com/300?text=Dumbbells",
                            Name = "Adjustable Dumbbell Set",
                            Price = 199.00m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 19,
                            Description = "500-piece colorful brick set for creative play.",
                            ImageUrl = "https://via.placeholder.com/300?text=Blocks",
                            Name = "Classic Building Blocks Set",
                            Price = 34.99m,
                            Stock = 85
                        },
                        new
                        {
                            Id = 20,
                            Description = "Complete exterior cleaning and detailing bundle.",
                            ImageUrl = "https://via.placeholder.com/300?text=Car+Wash+Kit",
                            Name = "Premium Car Wash & Wax Kit",
                            Price = 42.99m,
                            Stock = 35
                        });
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Reward")
                        .HasColumnType("int");

                    b.Property<int>("RewardValue")
                        .HasColumnType("int");

                    b.Property<decimal>("Threshold")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("Promotions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "10% Off Entire Order Over 500 RON",
                            Reward = 1,
                            RewardValue = 10,
                            Threshold = 500.00m,
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "5% Off Entire Order Over 200 RON",
                            Reward = 1,
                            RewardValue = 5,
                            Threshold = 200.00m,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Buy Any 5 Items, Get 15% Off Total",
                            Reward = 1,
                            RewardValue = 15,
                            Threshold = 5.00m,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            IsActive = false,
                            Name = "INACTIVE: 20% Off Mega Carts (1000+ RON)",
                            Reward = 1,
                            RewardValue = 20,
                            Threshold = 1000.00m,
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "15% Off Electronics Over 300 RON",
                            Reward = 1,
                            RewardValue = 15,
                            Threshold = 300.00m,
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            IsActive = true,
                            Name = "Buy 3 Clothing Items, Get 1 Free",
                            Reward = 0,
                            RewardValue = 1,
                            Threshold = 3.00m,
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 6,
                            IsActive = true,
                            Name = "20% Off Books When You Buy 2 or More",
                            Reward = 1,
                            RewardValue = 20,
                            Threshold = 2.00m,
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 9,
                            IsActive = true,
                            Name = "5% Off Health Essentials Over 100 RON",
                            Reward = 1,
                            RewardValue = 5,
                            Threshold = 100.00m,
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 8,
                            IsActive = false,
                            Name = "INACTIVE: Buy 2 Toys, Get 1 Free",
                            Reward = 0,
                            RewardValue = 1,
                            Threshold = 2.00m,
                            Type = 0
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Name = "10% Off Smart Fitness Watch",
                            ProductId = 1,
                            Reward = 1,
                            RewardValue = 10,
                            Threshold = 1.00m,
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Name = "Buy 2 T-Shirts, Get 1 Free",
                            ProductId = 4,
                            Reward = 0,
                            RewardValue = 1,
                            Threshold = 2.00m,
                            Type = 0
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Name = "15% Off Pro Gaming Laptop",
                            ProductId = 2,
                            Reward = 1,
                            RewardValue = 15,
                            Threshold = 1.00m,
                            Type = 0
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            Name = "Buy 4 Multivitamin Gummies, Get 2 Free",
                            ProductId = 10,
                            Reward = 0,
                            RewardValue = 2,
                            Threshold = 4.00m,
                            Type = 0
                        },
                        new
                        {
                            Id = 14,
                            IsActive = false,
                            Name = "INACTIVE: 50% Off Mystery Board Game",
                            ProductId = 9,
                            Reward = 1,
                            RewardValue = 50,
                            Threshold = 1.00m,
                            Type = 0
                        });
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("JwtId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@smartshopping.com",
                            PasswordHash = "$2a$11$DVPyXpSFG6C.ZRtuQQ7I6..dnE1/l99RJwMbXuBcdDCy6R0W/jJTG",
                            Role = 1,
                            Username = "admin_master"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "john@example.com",
                            PasswordHash = "$2a$11$DVPyXpSFG6C.ZRtuQQ7I6..dnE1/l99RJwMbXuBcdDCy6R0W/jJTG",
                            Role = 0,
                            Username = "john_doe"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jane@example.com",
                            PasswordHash = "$2a$11$DVPyXpSFG6C.ZRtuQQ7I6..dnE1/l99RJwMbXuBcdDCy6R0W/jJTG",
                            Role = 0,
                            Username = "jane_smith"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "test@example.com",
                            PasswordHash = "$2a$11$DVPyXpSFG6C.ZRtuQQ7I6..dnE1/l99RJwMbXuBcdDCy6R0W/jJTG",
                            Role = 0,
                            Username = "tester_account"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "deals@example.com",
                            PasswordHash = "$2a$11$DVPyXpSFG6C.ZRtuQQ7I6..dnE1/l99RJwMbXuBcdDCy6R0W/jJTG",
                            Role = 0,
                            Username = "deal_hunter"
                        });
                });

            modelBuilder.Entity("ProductCategories", b =>
                {
                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Cart", b =>
                {
                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("SmartShoppingAssistant.DataAccess.Entities.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.CartItem", b =>
                {
                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Order", b =>
                {
                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.OrderItem", b =>
                {
                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Promotion", b =>
                {
                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.Category", "Category")
                        .WithMany("Promotions")
                        .HasForeignKey("CategoryId");

                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.Product", "Product")
                        .WithMany("Promotions")
                        .HasForeignKey("ProductId");

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.RefreshToken", b =>
                {
                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Category", b =>
                {
                    b.Navigation("Promotions");
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Promotions");
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.User", b =>
                {
                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("Orders");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
